In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [6]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [13]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
# One square bracket
vector.ndim

1

In [15]:
# Two elements
vector.shape

torch.Size([2])

In [16]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([2, 2])

In [23]:
Tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [24]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [25]:
Tensor.ndim

3

In [26]:
Tensor.shape

torch.Size([2, 3, 3])

In [31]:
noisedImage = torch.rand(size=(128, 128, 3))
noisedImage.shape, noisedImage.ndim

(torch.Size([128, 128, 3]), 3)

In [32]:
zeros = torch.zeros(size=(2, 3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [34]:
ones = torch.ones(size=(2, 3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [35]:
zeroToTen = torch.arange(start=0, end=10, step=1)
zeroToTen

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
tenZeros = torch.zeros_like(input=zeroToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
halfTensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.half)
halfTensor.dtype

tensor([1., 2., 3.], dtype=torch.float16)

In [41]:
randomTensor = torch.rand(3, 4)

print(randomTensor)
print(randomTensor.shape)
print(randomTensor.dtype)
print(randomTensor.device)

tensor([[0.4649, 0.7382, 0.0981, 0.0406],
        [0.0356, 0.9555, 0.2580, 0.0828],
        [0.2062, 0.5446, 0.9403, 0.5686]])
torch.Size([3, 4])
torch.float32
cpu


In [42]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
tensor * 10

tensor([10, 20, 30])

In [44]:
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=torch.float32)

torch.manual_seed(6969)

linear = torch.nn.Linear(in_features=2, out_features=6)
output = linear(x)
x.shape, output, output.shape

(torch.Size([3, 2]),
 tensor([[ 0.1040, -0.7296,  2.4394,  0.8975, -0.7885, -0.2598],
         [-0.1540, -0.2838,  3.5086,  0.8361, -0.6079, -0.2564]],
        grad_fn=<AddmmBackward0>),
 torch.Size([2, 6]))

In [51]:
x.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [60]:
torch.manual_seed(6969)
tensorA = torch.rand(2, 3)
torch.manual_seed(6969)
tensorB = torch.rand(2, 3)

tensorA, tensorB, tensorA == tensorB

(tensor([[0.3936, 0.1828, 0.7001],
         [0.8782, 0.9346, 0.0731]]),
 tensor([[0.3936, 0.1828, 0.7001],
         [0.8782, 0.9346, 0.0731]]),
 tensor([[True, True, True],
         [True, True, True]]))

# EXERCISE

In [11]:
torch.manual_seed(0)
randomTensor = torch.rand(size=(7, 7))
randomTensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [62]:
torch.manual_seed(0)
randomTensorA = torch.rand(size=(1, 7))
torch.manual_seed(0)
randomTensorB = torch.rand(size=(1, 7))
randomTensorA.matmul(randomTensorB.T)

tensor([[1.5985]])

In [4]:
torch.manual_seed(1234)
cpuTensorA = torch.rand(size=(2, 3))
torch.manual_seed(1234)
cpuTensorB = torch.rand(size=(2, 3))

gpuTensorA = cpuTensorA.to("cuda")
gpuTensorB = cpuTensorB.to("cuda")

gpuMatMul = gpuTensorA.matmul(gpuTensorB.T)

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [7]:
torch.max(gpuMatMul), torch.min(gpuMatMul)

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [6]:
torch.argmax(gpuMatMul), torch.argmin(gpuMatMul)

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [10]:
torch.manual_seed(7)
randomTensor = torch.rand(size=(1, 1, 1, 10))
print(f"{randomTensor} {randomTensor.shape}")
randomTensor = torch.squeeze(randomTensor)
print(f"{randomTensor} {randomTensor.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
